/*
 * Hisense TV Remote for Flipper Zero
 *
 * A redesigned, more intuitive GUI for the Hisense TV remote application.
 * This version features a vertical layout designed to be used when holding
 * the Flipper sideways (rotated +90 degrees), with the IR sensor pointing at the TV.
 * This application showcases writting custom IR codes with the Flipper SDK.
 * Author: Tyler Berndt (original), Modified for Hisense
 * Website: https://purplefox.io
 */

#include <furi.h>
#include <furi_hal.h>
#include <gui/gui.h>
#include <input/input.h>
#include <notification/notification.h>
#include <notification/notification_messages.h> // For notification sequences
#include <gui/view_dispatcher.h>
#include <gui/view.h>
#include <gui/icon.h>

// The SDK infrared library
#include "infrared_signal.h"
// Header for icons generated by the build system from the 'images' folder
#include "hisense_icons.h"

// --- Button Definitions ---
typedef enum {
    Button_Power,
    Button_Capture,
    Button_Volume_Up,
    Button_Channel_Up,
    Button_Volume_Down,
    Button_Channel_Down,
    Button_Up,
    Button_Left,
    Button_Enter,
    Button_Right,
    Button_Down,
    Button_Back,
    Button_Mute,
    Button_Max, // Represents the total number of buttons
} TvButton;

// Struct to define the properties and layout of a single remote button
typedef struct {
    const char* label; // Text label for the button (or NULL if using icon)
    const Icon* icon; // Icon for the button (or NULL if using text)
    uint8_t x, y, w, h; // Position (x,y) and size (width, height)
    // Navigation links to other buttons for D-Pad controls
    TvButton nav_up;
    TvButton nav_down;
    TvButton nav_left;
    TvButton nav_right;
} RemoteButtonDef;

// --- Remote Layout Definition ---
// A vertical, single-column layout designed to be viewed with the Flipper
// held sideways (rotated +90 degrees). Navigation links are corrected for new logic.
static const RemoteButtonDef button_defs[Button_Max] = {
    // ID                 Label   Icon             X   Y   W   H   Up            Down          Left          Right
    [Button_Power]      = {"pwr",  NULL,           16,  2, 32,  8, Button_Power,       Button_Capture,     Button_Power,       Button_Power},

    // Capture Button - right under PWR
    [Button_Capture]    = {"cptr", NULL,          16, 14, 32, 10, Button_Power,       Button_Volume_Up,   Button_Capture,     Button_Capture},

    // Volume and Channel Rockers - shifted down
    [Button_Volume_Up]  = {NULL,   &I_volup24x21,   5, 26, 24, 21, Button_Capture,     Button_Volume_Down, Button_Volume_Up,   Button_Channel_Up},
    [Button_Channel_Up] = {NULL,   &I_chup24x21,   35, 26, 24, 21, Button_Capture,     Button_Channel_Down,Button_Volume_Up,   Button_Channel_Up},

    [Button_Volume_Down]= {NULL,   &I_voldown24x21, 5, 48, 24, 21, Button_Volume_Up,   Button_Up,          Button_Volume_Down, Button_Channel_Down},
    [Button_Channel_Down]={NULL,   &I_chdown24x21, 35, 48, 24, 21, Button_Channel_Up,  Button_Up,          Button_Volume_Down, Button_Channel_Down},

    // D-Pad - shifted down
    [Button_Up]         = {NULL,   &I_up7x4,       28, 73,  7,  4, Button_Channel_Down,Button_Enter,       Button_Up,          Button_Up},
    [Button_Enter]      = {NULL,   &I_center7x4,   28, 82,  7,  4, Button_Up,          Button_Volume_Down, Button_Left,        Button_Right},
    [Button_Left]       = {NULL,   &I_left7x4,     13, 82,  7,  4, Button_Enter,       Button_Enter,       Button_Left,        Button_Enter},
    [Button_Right]      = {NULL,   &I_right7x4,    47, 82,  7,  4, Button_Enter,       Button_Enter,       Button_Enter,       Button_Right},
    [Button_Down]       = {NULL,   &I_down7x4,     28, 93,  7,  4, Button_Enter,       Button_Back,        Button_Down,        Button_Down},

    // Bottom Row - shifted down
    [Button_Back]       = {"back", NULL,            4, 102, 26, 12, Button_Down,        Button_Back,        Button_Back,        Button_Mute},
    [Button_Mute]       = {"mute", NULL,           34, 102, 26, 12, Button_Down,        Button_Mute,        Button_Back,        Button_Mute},
};

// --- App Structures ---

// Model for the main view, holds the currently selected button
typedef struct {
    TvButton current_button;
    bool dpad_capture_mode; // D-Pad capture mode flag
} RemoteViewModel;

// Main application structure
typedef struct {
    ViewDispatcher* view_dispatcher;
    View* remote_view;
    NotificationApp* notifications;
} App;

// --- Function Prototypes ---
static void send_ir_code(TvButton button, NotificationApp* notifications);

// --- Core Functions ---

/**
 * @brief Draws the remote control UI on the canvas.
 * @param canvas The canvas to draw on.
 * @param model The view model containing the current state.
 */
static void app_draw_callback(Canvas* canvas, void* model) {
    RemoteViewModel* view_model = model;
    canvas_clear(canvas);

    // Draw all buttons in their unselected state first
    for(int i = 0; i < Button_Max; i++) {
        const RemoteButtonDef* btn = &button_defs[i];
        canvas_set_color(canvas, ColorBlack);
        
        if(btn->icon) {
            canvas_draw_icon(canvas, btn->x, btn->y, btn->icon);
        } else {
            canvas_draw_rframe(canvas, btn->x, btn->y, btn->w, btn->h, 3);
            canvas_set_font(canvas, FontSecondary);
            canvas_draw_str_aligned(
                canvas, btn->x + btn->w / 2, btn->y + btn->h / 2, AlignCenter, AlignCenter, btn->label);
        }
    }

    // Draw the selected button over the top to fix highlighting issues
    const RemoteButtonDef* selected_btn = &button_defs[view_model->current_button];
    canvas_set_color(canvas, ColorBlack);
    
    if(selected_btn->icon) {
        canvas_draw_box(canvas, selected_btn->x - 2, selected_btn->y - 2, selected_btn->w + 4, selected_btn->h + 4);
        canvas_set_color(canvas, ColorWhite);
        canvas_draw_icon(canvas, selected_btn->x, selected_btn->y, selected_btn->icon);
    } else {
        canvas_draw_rbox(canvas, selected_btn->x, selected_btn->y, selected_btn->w, selected_btn->h, 3);
        canvas_set_color(canvas, ColorWhite);
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(
            canvas,
            selected_btn->x + selected_btn->w / 2,
            selected_btn->y + selected_btn->h / 2,
            AlignCenter,
            AlignCenter,
            selected_btn->label);
    }

    // Draw D-Pad capture mode indicator
    if(view_model->dpad_capture_mode) {
        canvas_set_color(canvas, ColorBlack);
        canvas_draw_box(canvas, 0, 120, 64, 8);
        canvas_set_color(canvas, ColorWhite);
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(canvas, 32, 124, AlignCenter, AlignCenter, "capture mode");
    }
}

/**
 * @brief Handles user input from the D-pad and buttons, remapping for vertical orientation.
 * @param event The input event.
 * @param context The application context.
 * @return True if the event was handled, false otherwise.
 */
static bool app_input_callback(InputEvent* event, void* context) {
    App* app = context;
    bool handled = false;

    // Check if we're in D-Pad capture mode
    RemoteViewModel* view_model = view_get_model(app->remote_view);
    bool in_capture_mode = view_model->dpad_capture_mode;
    view_commit_model(app->remote_view, false);

    if(in_capture_mode) {
        // In capture mode: D-pad directly sends IR commands
        if(event->type == InputTypeShort || event->type == InputTypeRepeat) {
            switch(event->key) {
            case InputKeyUp:
                send_ir_code(Button_Up, app->notifications);
                handled = true;
                break;
            case InputKeyDown:
                send_ir_code(Button_Down, app->notifications);
                handled = true;
                break;
            case InputKeyLeft:
                send_ir_code(Button_Left, app->notifications);
                handled = true;
                break;
            case InputKeyRight:
                send_ir_code(Button_Right, app->notifications);
                handled = true;
                break;
            case InputKeyOk:
                send_ir_code(Button_Enter, app->notifications);
                handled = true;
                break;
            case InputKeyBack:
                // Short back in capture mode sends Back IR signal
                send_ir_code(Button_Back, app->notifications);
                handled = true;
                break;
            default:
                break;
            }
        } else if(event->type == InputTypeLong && event->key == InputKeyBack) {
            // Long back in capture mode exits capture mode
            with_view_model(
                app->remote_view,
                RemoteViewModel* model,
                { model->dpad_capture_mode = false; },
                true);
            handled = true;
        }
        return handled;
    }

    // Normal mode handling

    // Handle long press on Back button to exit app (only in normal mode)
    if(event->key == InputKeyBack && event->type == InputTypeLong) {
        view_dispatcher_stop(app->view_dispatcher);
        return true;
    }

    if(event->type != InputTypeShort && event->type != InputTypeRepeat) {
        return false;
    }

    if(event->key == InputKeyBack) {
        // Short back - just ignore in normal mode (long press handled above)
        handled = true;
    } else if(event->key == InputKeyOk) {
        with_view_model(
            app->remote_view,
            RemoteViewModel* model,
            {
                if(model->current_button == Button_Capture) {
                    // Activate D-Pad capture mode
                    model->dpad_capture_mode = true;
                } else {
                    send_ir_code(model->current_button, app->notifications);
                }
            },
            true);
        handled = true;
    } else {
        with_view_model(
            app->remote_view,
            RemoteViewModel* model,
            {
                const RemoteButtonDef* btn_def = &button_defs[model->current_button];
                if(model->current_button == Button_Enter) {
                    // Special D-Pad navigation when "OK" is selected
                    switch(event->key) {
                    case InputKeyUp:
                        model->current_button = Button_Up;
                        break;
                    case InputKeyDown:
                        model->current_button = Button_Down;
                        break;
                    case InputKeyLeft:
                        model->current_button = Button_Left;
                        break;
                    case InputKeyRight:
                        model->current_button = Button_Right;
                        break;
                    default:
                        break;
                    }
                } else {
                    // Standard navigation for all other buttons
                    switch(event->key) {
                    case InputKeyUp: // Physical Up -> UI Up
                        model->current_button = btn_def->nav_up;
                        break;
                    case InputKeyDown: // Physical Down -> UI Down
                        model->current_button = btn_def->nav_down;
                        break;
                    case InputKeyLeft: // Physical Left -> UI Left (column change)
                        model->current_button = btn_def->nav_left;
                        break;
                    case InputKeyRight: // Physical Right -> UI Right (column change)
                        model->current_button = btn_def->nav_right;
                        break;
                    default:
                        break;
                    }
                }
            },
            true);
        handled = true;
    }

    return handled;
}

/**
 * @brief Transmits the selected IR code using the SDK library.
 * @param button The button that was pressed.
 * @param notifications Notification app instance for vibration feedback.
 */
static void send_ir_code(TvButton button, NotificationApp* notifications) {
    notification_message(notifications, &sequence_single_vibro);
    notification_message(notifications, &sequence_blink_magenta_10);

    // Hisense NEC extended: full address and command as in IR file
    uint32_t address = 0x0000BF00; // 00 BF 00 00
    uint32_t command;

    switch(button) {
    case Button_Power:
        command = 0x0000F20D; // 0D F2 00 00
        break;
    case Button_Volume_Up:
        command = 0x0000BB44; // 44 BB 00 00
        break;
    case Button_Volume_Down:
        command = 0x0000BC43; // 43 BC 00 00
        break;
    case Button_Channel_Up:
        command = 0x0000B54A; // 4A B5 00 00
        break;
    case Button_Channel_Down:
        command = 0x0000B44B; // 4B B4 00 00
        break;
    case Button_Left:
        command = 0x0000E619; // 19 E6 00 00
        break;
    case Button_Right:
        command = 0x0000E718; // 18 E7 00 00
        break;
    case Button_Up:
        command = 0x0000E916; // 16 E9 00 00
        break;
    case Button_Down:
        command = 0x0000E817; // 17 E8 00 00
        break;
    case Button_Back:
        command = 0x0000B748; // 48 B7 00 00
        break;
    case Button_Enter:
        command = 0x0000EA15; // 15 EA 00 00
        break;
    case Button_Mute:
        command = 0x0000F10E; // 0E F1 00 00
        break;
    default:
        notification_message(notifications, &sequence_reset_rgb);
        return;
    }

    InfraredSignal* signal = infrared_signal_alloc();
    furi_check(signal);
    InfraredMessage message = {
        .protocol = InfraredProtocolNECext, .address = address, .command = command, .repeat = false};
    infrared_signal_set_message(signal, &message);
    infrared_signal_transmit(signal);
    infrared_signal_free(signal);

    furi_delay_ms(50);
    notification_message(notifications, &sequence_reset_rgb);
}

/**
 * @brief Allocates and initializes the application.
 * @return Pointer to the allocated App structure.
 */
static App* app_alloc() {
    App* app = malloc(sizeof(App));

    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);

    // Remote View
    app->remote_view = view_alloc();
    view_set_orientation(app->remote_view, ViewOrientationVertical);
    view_set_context(app->remote_view, app);
    view_allocate_model(app->remote_view, ViewModelTypeLockFree, sizeof(RemoteViewModel));
    with_view_model(
        app->remote_view,
        RemoteViewModel* model,
        {
            model->current_button = Button_Power;
            model->dpad_capture_mode = false;
        },
        true);
    view_set_draw_callback(app->remote_view, app_draw_callback);
    view_set_input_callback(app->remote_view, app_input_callback);
    view_dispatcher_add_view(app->view_dispatcher, 0, app->remote_view);

    // GUI
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    view_dispatcher_switch_to_view(app->view_dispatcher, 0);

    // Notifications
    app->notifications = furi_record_open(RECORD_NOTIFICATION);
    notification_message(app->notifications, &sequence_display_backlight_enforce_on);

    return app;
}

/**
 * @brief Frees all application resources.
 * @param app Pointer to the App structure to free.
 */
static void app_free(App* app) {
    furi_assert(app);

    notification_message(app->notifications, &sequence_display_backlight_enforce_auto);
    furi_record_close(RECORD_NOTIFICATION);

    view_dispatcher_remove_view(app->view_dispatcher, 0);
    view_free(app->remote_view);

    view_dispatcher_free(app->view_dispatcher);
    furi_record_close(RECORD_GUI);
    free(app);
}

/**
 * @brief Main entry point for the application.
 * @param p Unused parameter.
 * @return 0 on success.
 */
int32_t hisense_remote_app(void* p) {
    UNUSED(p);
    App* app = app_alloc();
    view_dispatcher_run(app->view_dispatcher);
    app_free(app);
    return 0;
}
